#ifndef __frmAcerca__
#define __frmAcerca__

/**
@file
Subclass of frmAcercaClass, which is generated by wxFormBuilder.
*/

#include "gui.h"

/** Implementing frmAcercaClass */
class frmAcerca : public frmAcercaClass
{
protected:
	// Handlers for frmAcercaClass events.
	void cmdCerrarClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	frmAcerca( wxWindow* parent );
};

#endif // __frmAcerca__
