#ifndef __frmMain__
#define __frmMain__

/**
@file
Subclass of frmMainClass, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include "systray.h"

/** Implementing frmMainClass */
class frmMain : public frmMainClass
{
protected:
	// Handlers for frmMainClass events.
	void AlCerrar( wxCloseEvent& event );
	void cmdPonerClick( wxCommandEvent& event );
	void mnuOpcionesClick( wxCommandEvent& event );
	void mnuSalirClick( wxCommandEvent& event );
	void mnuF1Click( wxCommandEvent& event );
	void mnuAcercaClick( wxCommandEvent& event );
	
public:
	systray *iconobandeja;
	/** Constructor */
	frmMain( wxWindow* parent );
};

#endif // __frmMain__
